### ISSUE TITLE
Sonderzeichen bei aktuell abfrage

### ISSUE THREAD

**Issue by Luftloch80** [alexa-d/alexa-openwebif#108]
wenn eine Sendung ein "&" enthält bekommt man keine Antwort 
ZB Mike & Molly

**Comment by fabsi88** [comment]
Hi @Luftloch80,

danke für dein Ticket.
Ich gucke es mir an.

**Comment by fabsi88** [comment]
Hi,
Ich habe PR #109 eröffnet und nach einem Review von @Extrawurst wird der Code in den Master übernommen und der Fehler ist damit behoben

**Comment by Luftloch80** [comment]
Super das ging ja schnell. 
Was ich noch beim testen festgestellt habe ich das es auf die Pause/stop Funktion keine Antwort gegeben hat und der Befehl auch immer als Pause genommen wird und niemals als stop Taste. 
Auch wenn man stop zu Enigma sagt

**Comment by fabsi88** [comment]
Mach dazu bitte ein separates Ticket auf und gib mir wichtige Infos wie:
- Box Type (VU+, Dreambox etc.)
- Image mit Version (z.B. VTi Image 8)
Die Pause / Fortsetzen und Stop Befehle basieren auf KeyMaps die bei jedem Image anders sein können etc

**Comment by Luftloch80** [comment]
Glaub "?" Geht auch nicht
