### ISSUE TITLE
stop/Pause VTI 11

### ISSUE THREAD

**Issue by Luftloch80** [alexa-d/alexa-openwebif#110]
Es wird immer Pause gemacht anstatt stop
keymaps habe ich getestet die sind richtig vielleicht erkennt er den boxtype nicht richtig 

Und der alexa Output ist auch null nach dem befehel

openvuplus 3.0 2017-02-17-vti-master (a480ee2) VTi 11.0.1. 3.13.5-20161228.r0 OWIF 1.2.0 0 Solo² 00:1d:ec:05:02:ce False 192.168.0.8 255.255.255.0 192.168.0.1 ATA(SAMSUNG HM500JI) 465.8 GB 247.6 GB Tuner A BCM7356 DVB-S2 NIM (internal) (DVB-S2) Tuner B BCM7356 DVB-S2 NIM (internal) (DVB-S2) 0 0 0 0x0 0 0 0 0 N/A 0 0 0

**Comment by fabsi88** [comment]
Hi, danke für die Info.
Ich kümmer mich drum. Habe genau das gleiche Setup ;-) Hatte die Funktion aber mit einer älteren VTI Version entwickelt. Scheinbar wurde hier was geändert.

**Comment by Luftloch80** [comment]
Gerne. Habe auch ein wenig mit den zap.d alias Namen gespielt. Läuft bei mir jetzt habe fast nur HD Kanäle und sage HD aber nicht dazu. Wird glaub extrem schwierig alle Fälle für viele User abzudecken

**Comment by Luftloch80** [comment]
Habt ihr für v2 geplant ähnlich wie beim kodi skill auf Filme und Serien auf dem NAS oder HDD zuzugreifen?

**Comment by fabsi88** [comment]
Ja das mit den Aliasen ist ein riesen Problem. Davon ab das viele nicht alles in HD haben, gibt es auch noch Unterschiede in den Servicenamen bei dern verschiedenen Providern (Sat / Kabel - Unitymeda, KabelBW etc.) 
Bitte sende mir mal deine zap.d an fabian@wallentowitz.de 

Für V2 ist geplant Filme die aufgenommen wurden oder auf der HDD liegen per Kommando abzuspielen.

**Comment by fabsi88** [comment]
Thema ist gefixt. Die Utterances müssen angepasst werden. Siehe den entsprechenden Commit
