### ISSUE TITLE
Wie geht das Beta Testing

### ISSUE THREAD

**Issue by Oliver1981** [alexa-d/alexa-openwebif#125]
Habe auf den Link geklickt aber ich bekomme den skill nicht in die App. Da ich nicht zum Beta testen eingeladen bin.  Was mache ich flach. Oliver.geesing@aol.de

**Comment by fabsi88** [comment]
Wie es scheint muss ich euch doch eintragen. Hab dich eingetragen.

**Comment by fabsi88** [comment]
Readme aktualisiert
