### ISSUE TITLE
add more aliases

### ISSUE THREAD

**Issue by fabsi88** [alexa-d/alexa-openwebif#83]

**Comment by Polymorph-78** [comment]
Hier findest du auch noch ein paar aliases vielleicht hilft es dir ja.
https://www.amzecho.de/yonomi-f58/tv-umschalten-rtl-pro7-wird-nicht-gefunden--t538.html

PS.: Meine Kinder würden sich bestimmt noch über KIKA freuen. :-D

**Comment by fabsi88** [comment]
Danke für die Infos! Werden wir berücksichtigen

**Comment by fabsi88** [comment]
@Polymorph-78 
Umschalten auf Kika funktioniert ;-)

**Comment by Polymorph-78** [comment]
Danke @fabsi88.

Freue mich schon auf den Skill.
