### ISSUE TITLE
IntentSleepTimer not working due to AMAZON.DURATION Format

### ISSUE THREAD

**Issue by fabsi88** [alexa-d/alexa-openwebif#86]
Amazon provides sth. like `PT10M` for 10 minutes. We expect an integer. We have two options:
1) parse amazon value
2) change to number?

@Extrawurst  What are you thinking about this?

**Comment by Extrawurst** [comment]
actually the returned duration has a standardized format ISO-8601 (see https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#duration) 
std.datetime supports the same format: https://dlang.org/phobos/std_datetime.html

**Comment by fabsi88** [comment]
It's right that Amazon uses the ISO 8601 duration format. But Duration is only a part of the complete standard - which is used by dlang as well. But in my point of view there is no "parsing" function to convert a ISO-8601 string to an duration object.
